INSERT INTO global_iot_events
SELECT scada.amplitude100 , 
scada.amplitude500 , 
scada.amplitude1000 , 
scada.lownoise , 
scada.midnoise ,
scada.highnoise , 
scada.amps , 
scada.ipaddress , 
scada.host_name ,
scada.macaddress , 
scada.endtime , 
scada.runtime , 
scada.starttime , 
scada.cpu , 
scada.cpu_temp , 
scada.diskusage , 
scada.memory , 
scada.id , 
scada.temperature , 
scada.adjtemp , 
scada.adjtempf , 
scada.temperaturef , 
scada.pressure , 
scada.humidity , 
scada.lux , 
scada.proximity , 
scada.oxidising , 
scada.reducing , 
scada.nh3 , 
scada.gasko,
energy.current, 
energy.voltage ,
energy.power ,
energy.total,
energy.deviceId, 
energy.alias ,
energy.dev_name,
energy.icon_hash,
energy.relay_state,
energy.on_time,
energy.active_mode, 
energy.feature,
energy.updating,
energy.rssi,
energy.led_off,
energy.latitude,
energy.longitude,
energy.index,
energy.zone_str,
energy.tz_str ,
energy.dst_offset,
energy.current_consumption ,
energy.devicetime ,
energy.ledon ,
energy.fanstatus,
airun.image_filename
FROM energy,
     airun,
     scada
WHERE
    energy.systemtime = airun.systemtime 
AND
    scada.systemtime = energy.systemtime;
